# Generated by Django 4.2.13 on 2024-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('conversation_id', models.BigIntegerField(default=0)),
                ('model', models.CharField(default='', max_length=50)),
                ('role', models.CharField(default='', max_length=50)),
                ('text', models.TextField(default='')),
                ('total_tokens', models.IntegerField(default=0)),
                ('detail', models.JSONField(default=dict, max_length=2500)),
            ],
            options={
                'index_together': {('user_name', 'conversation_id')},
            },
        ),
    ]
